//Sample data
const properties = [
   {
    id: 0,
    beds: 2,
    baths: 2,
    area: 13,
    price: 1000,
    image: "/images/property-0.jpg",
    type:"Villa",
  },
  {
    image: "/images/property-1.jpg",
    id: 1,
    beds: 3,
    baths: 1,
    area: 17,
    price: 2000,
    type:"Apartment",
  },
   {
    image: "/images/property-2.jpg",
    id: 2,
    beds: 4,
    baths: 3,
    area: 25,
    price: 3000,
    type:"House",
  },
   {
    image: "/images/property-3.jpg",
    id: 3,
    beds: 5,
    baths: 1,
    area: 15,
    price: 4000,
    type:"House",
  },
  
   {
    image: "/images/property-4.jpg",
    id: 4,
    beds: 2,
    baths: 3,
    area: 20,
    price: 5000,
    type:"House",
  },
   {
    image: "/images/property-5.jpg",
    id: 5,
    beds: 2,
    baths: 1,
    area: 30,
    price: 6000,
    type:"Villa",
  },
   {
    image: "/images/property-6.jpg",
    id: 6,
    beds: 3,
    baths: 1,
    area: 23,
    price: 7000,
    type:"Bungalow",
  },
  {
    image: "/images/property-7.jpg",
    id: 7,
    beds: 2,
    baths: 1,
    area: 35,
    price: 8000,
    type:"House",
  },
  {
    image: "/images/property-8.jpg",
    id: 8,
    beds: 3,
    baths: 2,
    area: 30,
    price: 9000,
    type:"Bungalow",
  },
   {
    image: "/images/property-9.jpg",
    id: 9,
    beds: 4,
    baths: 2,
    area: 32,
    price: 7500,
    type:"House",
  },
  {
    image: "/images/property-10.jpg",
    id: 10,
    beds: 2,
    baths: 1,
    area: 25,
    price: 6500,
    type:"House",
  },
   {
    image: "/images/property-11.jpg",
    id: 11,
    beds: 1,
    baths: 1,
    area: 10,
    price: 2500,
    type:"Villa",
  },
   {
    image: "/images/property-12.jpg",
    id: 12,
    beds: 2,
    baths: 1,
    area: 15,
    price: 4500,
    type:"House",
  },
   {
    image: "/images/property-13.jpg",
    id: 13,
    beds: 5,
    baths: 2,
    area: 37,
    price: 10000,
    type:"Villa",
  },
  {
    image: "/images/property-14.jpg",
    id: 14,
    beds: 2,
    baths: 1,
    area: 20,
    price: 3500,
    type:"Villa",
  },
  {
    image: "/images/property-15.jpg",
    id: 15,
    beds: 1,
    baths: 1,
    area: 5,
    price: 1500,
    type:"Bungalow",
  },
   {
    image: "/images/property-16.jpg",
    id: 16,
    beds: 5,
    baths: 3,
    area: 45,
    price: 12000,
    type:"House"
  },
   {
    image: "/images/property-17.jpg",
    id: 17,
    beds: 3,
    baths: 3,
    area: 45,
    price: 11500,
    type:"Apartment",
  },
   {
    image: "/images/property-18.jpg",
    id: 18,
    beds: 5,
    baths: 4,
    area: 45,
    price: 15000,
    type:"House",
  },
   {
    image: "/images/property-19.jpg",
    id: 19,
    beds: 4,
    baths: 4,
    area: 37,
    price: 10500,
    type:"Villa",
  },
];
export default properties;
